# Generated by Django 5.1 on 2025-05-29 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject_template', models.CharField(max_length=300)),
                ('body_template', models.TextField()),
                ('variables_help', models.TextField(help_text='Available template variables')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SYNOPSIS_APPROVAL', 'Synopsis Needs Approval'), ('EVALUATOR_ASSIGNMENT', 'Evaluator Assignment Required'), ('EVALUATOR_CONFIRMED', 'Evaluator Confirmed'), ('PROJECT_SUBMITTED', 'Project Submitted for Evaluation'), ('EVALUATION_COMPLETED', 'Evaluation Completed'), ('VIVA_READY', 'Project Ready for Viva'), ('PAYMENT_REQUIRED', 'Payment to Evaluator Required'), ('PROJECT_COMPLETED', 'Project Completed'), ('EMAIL_FAILED', 'Email Communication Failed')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailCommunication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_type', models.CharField(choices=[('INVITATION', 'Evaluation Invitation'), ('REMINDER', 'Reminder'), ('PROJECT_SUBMISSION', 'Project Submission for Review'), ('FOLLOW_UP', 'Follow-up'), ('ACCEPTANCE', 'Acceptance Confirmation'), ('REJECTION', 'Rejection Notification'), ('EVALUATION_REQUEST', 'Evaluation Request')], max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('sent_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('OPENED', 'Opened'), ('REPLIED', 'Replied'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('BOUNCED', 'Bounced'), ('FAILED', 'Failed')], default='SENT', max_length=20)),
                ('attempt_number', models.IntegerField(default=1, help_text='1st, 2nd, or 3rd attempt')),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('response_content', models.TextField(blank=True)),
                ('message_id', models.CharField(blank=True, help_text='Message Subject id we use to track the email', max_length=200)),
                ('attachments_sent', models.JSONField(default=list, help_text='List of attachment file names')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.evaluator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='projects.project')),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
    ]
