# Generated by Django 5.1 on 2025-05-31 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('projects', '0005_projectevaluatorpool_last_email_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcommunication',
            name='attempt_number',
        ),
        migrations.RemoveField(
            model_name='emailcommunication',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='emailcommunication',
            name='project',
        ),
        migrations.RemoveField(
            model_name='emailcommunication',
            name='response_content',
        ),
        migrations.RemoveField(
            model_name='emailcommunication',
            name='response_date',
        ),
        migrations.AddField(
            model_name='emailcommunication',
            name='eval_pool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.projectevaluatorpool'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailcommunication',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('NOT SENT', 'Not Sent'), ('FAILED', 'Failed')], default='SENT', max_length=20),
        ),
    ]
