# Generated by Django 5.2.3 on 2025-07-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_remove_emailcommunication_attempt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='attachments',
            field=models.JSONField(default=list, help_text='List of attachment file names'),
        ),
    ]
