# Generated by Django 5.2.3 on 2025-07-02 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_adminnotification_attachments'),
        ('projects', '0008_projectevaluatorpool_report_retry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.project'),
        ),
    ]
