# Generated by Django 5.2.3 on 2025-07-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_alter_adminnotification_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('gmail', 'Gmail'), ('drive', 'Drive'), ('combined', 'Combined')], default='combined', max_length=50)),
                ('token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_uri', models.URLField()),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('scopes', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Google OAuth Token',
                'verbose_name_plural': 'Google OAuth Tokens',
            },
        ),
    ]
