# Generated by Django 5.2.3 on 2025-07-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_googleoauthtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('RECEIVED_EMAIL', 'Received Email'), ('SYNOPSIS_APPROVAL', 'Synopsis Needs Approval'), ('EVALUATOR_ASSIGNMENT', 'Evaluator Assignment Required'), ('EVALUATOR_CONFIRMED', 'Evaluator Confirmed'), ('PROJECT_SUBMITTED', 'Project Submitted for Evaluation'), ('EVALUATION_COMPLETED', 'Evaluation Completed'), ('VIVA_READY', 'Project Ready for Viva'), ('PAYMENT_REQUIRED', 'Payment to Evaluator Required'), ('PROJECT_COMPLETED', 'Project Completed'), ('EMAIL_FAILED', 'Email Communication Failed')], max_length=30),
        ),
    ]
