# Generated by Django 5.2.3 on 2025-07-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_alter_adminnotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='google_message_id',
            field=models.CharField(blank=True, help_text='Message Subject id we use to track the email', max_length=200),
        ),
    ]
