# Generated by Django 5.2.3 on 2025-07-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_adminnotification_google_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='from_email',
            field=models.EmailField(default='unknown@dare.com', max_length=254),
            preserve_default=False,
        ),
    ]
