# Generated by Django 5.1 on 2025-05-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdstudent',
            name='email',
            field=models.EmailField(default='senthil@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
