# Generated by Django 5.1 on 2025-05-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_phdstudent_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluator',
            name='average_response_time_days',
        ),
        migrations.RemoveField(
            model_name='evaluator',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='evaluator',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='evaluator',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='evaluator',
            name='total_evaluations',
        ),
    ]
