# Generated by Django 5.1 on 2025-05-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_evaluator_average_response_time_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluator',
            name='priority_score',
        ),
    ]
