# Generated by Django 5.2.3 on 2025-07-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_evaluator_priority_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='name',
            field=models.CharField(default='user', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phdstudent',
            name='name',
            field=models.CharField(default='user', max_length=200),
            preserve_default=False,
        ),
    ]
