# Generated by Django 5.2.3 on 2025-07-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_guide_name_phdstudent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.CharField(choices=[('FACULTY_OF_AGRICULTURE', 'Faculty of Agriculture'), ('FACULTY_OF_ARTS', 'Faculty of Arts'), ('FACULTY_OF_DENTISTRY', 'Faculty of Dentistry'), ('FACULTY_OF_EDUCATION', 'Faculty of Education'), ('FACULTY_OF_ENGINEERING_TECHNOLOGY', 'Faculty of Engineering & Technology'), ('FACULTY_OF_FINE_ARTS', 'Faculty of Fine Arts'), ('FACULTY_OF_INDIAN_LANGUAGES', 'Faculty of Indian Languages'), ('FACULTY_OF_MARINE_SCIENCES', 'Faculty of Marine Sciences'), ('FACULTY_OF_MEDICINE', 'Faculty of Medicine'), ('FACULTY_OF_SCIENCE', 'Faculty of Science')], default='FACULTY_OF_ENGINEERING_TECHNOLOGY', max_length=200),
        ),
    ]
