# Generated by Django 5.1 on 2025-05-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectevaluatorpool',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
