# Generated by Django 5.1 on 2025-05-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectevaluatorpool_retry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectevaluatorpool',
            name='priority_order',
            field=models.IntegerField(help_text='1-5 for each type (foreign/indian) & Higher score = higher priority'),
        ),
    ]
