# Generated by Django 5.1 on 2025-05-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectevaluatorpool_priority_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='referel_id',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
