# Generated by Django 5.1 on 2025-05-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_referel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectevaluatorpool',
            name='last_email_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
