# Generated by Django 5.2.3 on 2025-06-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectevaluatorpool',
            name='next_email_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='referel_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
