# Generated by Django 5.2.3 on 2025-06-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectevaluatorpool_next_email_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectevaluatorpool',
            name='report_retry_count',
            field=models.IntegerField(default=0, help_text='Retry count for project submission emails'),
        ),
    ]
