# Generated by Django 5.2.3 on 2025-07-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectevaluatorpool_report_retry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectevaluatorpool',
            name='report_last_email_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectevaluatorpool',
            name='report_next_email_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
