# Generated by Django 5.2.3 on 2025-07-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectevaluatorpool_report_last_email_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectevaluatorpool',
            name='retry_count',
            field=models.IntegerField(default=0, help_text='Retry count for approach'),
        ),
    ]
