# Generated by Django 5.2.3 on 2025-07-31 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_projectevaluatorpool_retry_count'),
        ('users', '0006_department_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionedProjectEvaluatorPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(help_text='Incremental version for evaluator set per project')),
                ('priority_order', models.IntegerField()),
                ('approach_mail_count', models.IntegerField(default=0)),
                ('report_mail_count', models.IntegerField(default=0)),
                ('next_approach_email_date', models.DateTimeField(blank=True, null=True)),
                ('next_evaluation_email_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.evaluator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versioned_evaluator_pool', to='projects.project')),
            ],
            options={
                'ordering': ['evaluator__evaluator_type', 'priority_order'],
                'unique_together': {('project', 'evaluator', 'version')},
            },
        ),
    ]
