# Generated by Django 5.2.3 on 2025-07-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_versionedprojectevaluatorpool'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionedprojectevaluatorpool',
            name='last_approach_email_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='versionedprojectevaluatorpool',
            name='last_evaluation_email_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
